### PR TITLE
A11y: set aria-expanded to the toggle button.

### PR DESCRIPTION
**Pull request by Carreau**
Quansight-Labs/czi-scientific-python-mgmt#77

The second commit also run prettify to fix some formatting issues.

### CODE REVIEW

**Comment by Carreau** [comment]
@gabalafou

**Review by trallard — APPROVED** [review]

**Review by gabalafou — APPROVED** [review]
Thank you, this looks good to go!

**Comment by gabalafou** [comment]
Just for the record, I built the docs locally with `tox run -e docs-live` and tested the button on the page with VoiceOver in expanded and collapsed state, as well as checked the accessibility tree.

**Comment by choldgraf** [comment]
thanks for the improvement, and for the follow-up linting update!

**Comment by gabalafou** [comment]
I'm interested :)

**Pull request merged**
