### PR TITLE
zindex

### LINKED ISSUE #23: Isn't z-index: 999 a bit excessive?
I don't know what the conventions are around this, but 999 seems a bit high to me.

The highest value mentioned at https://developer.mozilla.org/en-US/docs/Web/CSS/z-index is 289.

And at https://drafts.csswg.org/css2/#propdef-z-index it seems to be 3.

Wouldn't something like 99 be more reasonable?

Right now, this is in conflict with [my Sphinx theme](https://insipid-sphinx-theme.readthedocs.io/). I could of course raise my conflicting `z-index`, but when does the arms race end?

### PR DESCRIPTION
**Pull request by choldgraf**
closes #23

### CODE REVIEW

**Comment by choldgraf** [comment]
@mgeier look OK to you?

**Comment by mgeier** [comment]
Looks great!

**Comment by choldgraf** [comment]
@mgeier I cut a release as well in case you'd like to use this

**Comment by mgeier** [comment]
Thanks a lot! It's not urgent though. I was just playing around with it in preparation for continuing work on https://github.com/spatialaudio/nbsphinx/pull/436. But that has time ...

I'd still need #26 to be fixed anyway.

Also, there are some minor button CSS issues when using other themes, I guess I'll open a new issue for that in the near future.

**Pull request merged**
